// Surname / shorthand → full ESPN display name (exact, including accents)
export const NAMES = {
  "Scheffler":           "Scottie Scheffler",
  "McIlroy":             "Rory McIlroy",       "Mcilroy":          "Rory McIlroy",
  "Rahm":                "Jon Rahm",
  "Aberg":               "Ludvig Åberg",
  "DeChambeau":          "Bryson DeChambeau",  "Dechambeau":       "Bryson DeChambeau",
  "Xander":              "Xander Schauffele",
  "Spieth":              "Jordan Spieth",
  "Rose":                "Justin Rose",
  "Morikawa":            "Collin Morikawa",
  "Matsuyama":           "Hideki Matsuyama",
  "Fitzpatrick":         "Matt Fitzpatrick",
  "Fleetwood":           "Tommy Fleetwood",
  "Hovland":             "Viktor Hovland",
  "Reed":                "Patrick Reed",
  "Koepka":              "Brooks Koepka",
  "Thomas":              "Justin Thomas",
  "Cantlay":             "Patrick Cantlay",
  "Henley":              "Russell Henley",
  "Kim":                 "Si Woo Kim",         "Si Woo Kim":       "Si Woo Kim",
  "SW Kim":              "Si Woo Kim",
  "M Kim":               "Michael Kim",
  "MW Lee":              "Min Woo Lee",         "Min Woo Lee":      "Min Woo Lee",
  "Scott":               "Adam Scott",
  "MacIntyre":           "Robert MacIntyre",
  "Gotterup":            "Chris Gotterup",
  "Young":               "Cameron Young",
  "Im":                  "Sungjae Im",
  "Johnson":             "Dustin Johnson",      "DJ":               "Dustin Johnson",
  "Conners":             "Corey Conners",
  "Knapp":               "Jake Knapp",
  "Day":                 "Jason Day",
  "Hatton":              "Tyrrell Hatton",
  "Homa":                "Max Homa",
  "Burns":               "Sam Burns",
  "Lowry":               "Shane Lowry",
  "Straka":              "Sepp Straka",
  "Berger":              "Daniel Berger",
  "English":             "Harris English",
  "Bradley":             "Keegan Bradley",
  "Kitayama":            "Kurt Kitayama",
  "McNealy":             "Maverick McNealy",
  "Bridgeman":           "Jacob Bridgeman",
  "Spaun":               "J.J. Spaun",
  "Hojgaard":            "Rasmus Højgaard",    "R Hojgaard":       "Rasmus Højgaard",
  "N Hojgaard":          "Nicolai Højgaard",   "N. Hojgaard":      "Nicolai Højgaard",
  "Rai":                 "Aaron Rai",
  "Bhatia":              "Akshay Bhatia",
  "Smith":               "Cameron Smith",
  "Noren":               "Alex Noren",
  "Woodland":            "Gary Woodland",
  "Harman":              "Brian Harman",
  "Clark":               "Wyndham Clark",
  "Riley":               "Davis Riley",
  "Fox":                 "Ryan Fox",
  "Garcia":              "Sergio García",
  "Willett":             "Danny Willett",
  "Schwartzel":          "Charl Schwartzel",
  "Watson":              "Bubba Watson",
  "Greyserman":          "Max Greyserman",
  "McCarty":             "Matt McCarty",
  "Taylor":              "Nick Taylor",
  "Echavarria":          "Nico Echavarria",
  "Stevens":             "Sam Stevens",
  "Campbell":            "Brian Campbell",
  "Potgieter":           "Aldrich Potgieter",
  "Couples":             "Fred Couples",
  "Singh":               "Vijay Singh",
  "McKibbin":            "Tom McKibbin",        "Mckibbin":         "Tom McKibbin",
  "Jarvis":              "Casey Jarvis",
  "Novak":               "Andrew Novak",
  "Reitan":              "Kristoffer Reitan",
  "Brennan":             "Michael Brennan",
  "Fang":                "Ethan Fang",
  "Gerard":              "Ryan Gerard",
  "Griffin":             "Ben Griffin",
  "Hall":                "Harry Hall",
  "Keefer":              "Johnny Keefer",
  "Li":                  "Haotong Li",
  "Ortiz":               "Carlos Ortiz",
  "Penge":               "Marco Penge",
  "Neergard-Petersen":   "Rasmus Neergaard-Petersen",
};
